micronaut:
  application:
    name: keyManagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManagerGrpc:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 5

jackson:
  serialization:
    writeDatesAsTimestamps: false